####################
#CommandCountPlugin#
####################

# レイドの時間を設定
# レイドを行う間隔を設定してください。
days: 7
hours: 0
minutes: 0

# スコアボードの設定
# スコアボードの更新速度を秒単位で設定してください。
updateTime: 10

# スコアの設定
# コマンドを実行した際の加算スコアの設定をします。
addScore: 1

# mysqlの設定
mysql:
  host: localhost
  port: 3306
  user: root
  pass: mk871396
  db: commandCountDatabase