####################
#CommandCountPlugin#
####################

# レイドの時間を設定
# レイドを行う間隔を設定してください。
days: 7
hours: 0
minutes: 0

# スコアボードの設定
# スコアボードの更新速度を秒単位で設定してください。
updateTime: 10

# mysqlの設定
mysql:
  host: localhost
  port: 3306
  user: root
  pass: m871396
  db: commandCountDatabase