####################
#CommandCountPlugin#
####################

# 何Tickおきにスコアボードを更新するかを設定します。
updateTime: 1200
# レイドを何秒間行うのかを設定します。
countTime: 10

# mysqlの設定
mysql:
  host: localhost
  port: 3306
  user: root
  pass: m871396
  db: commandCountDatabase