####################
#CommandCountPlugin#
####################

# レイドの時間を設定
# レイドを行う間隔を設定してください。
# 注意！必ず整数を入れてください。
days: 7       # 日にち
hours: 0      # 時間
minutes: 0    # 分

# スコアボードの設定
# スコアボードの更新速度を秒単位で設定します。
# 注意！必ず整数を入れてください。
updateTime: 10

# スコアの設定
# コマンドを実行した際の加算スコアの設定をします。
# 注意！必ず整数を入れてください。
addScore: 1

# 納品の設定
# 納品する際のコマンドのクールタイムを秒単位で設定します。
# 注意！必ず少数を入れてください。
coolTime: 0.5

# mysqlの設定
mysql:
  host: localhost
  port: 3306
  user: root
  pass: mk871396
  db: commandCountDatabase